backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "proyectos"
    label: "Proyectos del Museo de Memorias Vivas"
    folder: "src/content/proyectos"
    create: true
    slug: "{{number}}-{{slug}}"
    fields:
      - { label: "Número", name: "number", widget: "number" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Lugar", name: "place", widget: "string" }
      - { label: "Colectivo/Autor", name: "author", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text", required: false }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Cuerpo", name: "body", widget: "markdown", required: false }

  - name: "pages"
    label: "Páginas"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
